elec1 <- read.table("household_power_consumption.txt", nrows = 1, sep = ";", head = T)
house <- read.table("household_power_consumption.txt", skip = 66637, nrows = 2880, sep = ";", head = F, na.string = "?")
colnames(house) <- names(elec1)
png('plot4.png', width = 480, height = 480, units = "px")
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))
plot(c(1:2880), house$Global_active_power, xaxt = "n", type = "n", xlab = "", ylab = "Global Active Power (kilowatts)")
lines(c(1:2880), house$Global_active_power)
axis(1, at = c(1, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
plot(c(1:2880), house$Voltage, xaxt = "n", type = "n", xlab = "datetime", ylab = "Voltage")
lines(c(1:2880), house$Voltage)
axis(1, at = c(1, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
plot(c(1:2880), house$Sub_metering_1, xaxt = "n", type = "n", xlab = "", ylab = "Energy sub metering")
lines(c(1:2880), house$Sub_metering_1)
lines(c(1:2880), house$Sub_metering_2, col = "red")
lines(c(1:2880), house$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n")
axis(1, at = c(1, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
plot(c(1:2880), house$Global_reactive_power, xaxt = "n", type = "n", ylab = "Global_reactive_power", xlab = "datetime")
lines(c(1:2880), house$Global_reactive_power)
axis(1, at = c(1, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
dev.off()