elec1 <- read.table("household_power_consumption.txt", nrows = 1, sep = ";", head = T)
house <- read.table("household_power_consumption.txt", skip = 66637, nrows = 2880, sep = ";", head = F, na.string = "?")
colnames(house) <- names(elec1)
png('plot3.png', width = 480, height = 480, units = "px")
plot(c(1:2880), house$Sub_metering_1, xaxt = "n", type = "n", xlab = "", ylab = "Energy sub metering")
lines(c(1:2880), house$Sub_metering_1)
lines(c(1:2880), house$Sub_metering_2, col = "red")
lines(c(1:2880), house$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
axis(1, at = c(1, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
dev.off()
